# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=250)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('pan', models.CharField(blank=True, max_length=250, null=True)),
                ('tan', models.CharField(blank=True, max_length=250, null=True)),
                ('pf_code', models.CharField(blank=True, max_length=250, null=True)),
                ('pt_certificate_no', models.CharField(blank=True, max_length=250, null=True)),
                ('esi_code', models.CharField(blank=True, max_length=250, null=True)),
                ('license_no', models.CharField(blank=True, max_length=250, null=True)),
                ('inactive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
