# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 10:19
from __future__ import unicode_literals

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Please enter up to 9 characters ONLY', max_length=250, validators=[company.models.validate_excess])),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('inactive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Please enter up to 9 characters ONLY', max_length=250, validators=[company.models.validate_excess])),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('info', models.TextField()),
                ('inactive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(help_text='Please enter up to 9 characters ONLY', max_length=250, validators=[company.models.validate_excess]),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
