# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20160822_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='max_working_full',
            field=models.TimeField(blank=True, null=True, verbose_name='Maximum working hours for full day'),
        ),
        migrations.AddField(
            model_name='shift',
            name='min_working_half',
            field=models.TimeField(blank=True, null=True, verbose_name='Minimum working hours for half day'),
        ),
        migrations.AddField(
            model_name='shift',
            name='total_working_hours',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
    ]
