# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 12:02
from __future__ import unicode_literals

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20160822_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Please enter up to 9 characters only', max_length=250, validators=[company.models.validate_excess])),
                ('name', models.CharField(max_length=250)),
                ('common_week_off', models.CharField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], max_length=250, verbose_name='Common week off')),
                ('first_week_off', models.DateField(blank=True, null=True, verbose_name='First Weekend')),
                ('second_week', models.DateField(blank=True, null=True, verbose_name='Second Weekend')),
                ('third_week', models.DateField(blank=True, null=True, verbose_name='Third Weekend')),
                ('fourth_week', models.DateField(blank=True, null=True, verbose_name='Fourth Weekend')),
                ('fifth_week', models.DateField(blank=True, null=True, verbose_name='Fifth Weekend')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
