# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 12:12
from __future__ import unicode_literals

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_weekoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Please enter up to 9 characters only', max_length=250, validators=[company.models.validate_excess])),
                ('name', models.CharField(max_length=250)),
                ('account_no', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('ifsc_code', models.CharField(max_length=250)),
                ('primary', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Please enter up to 9 characters only', max_length=250, validators=[company.models.validate_excess])),
                ('name', models.CharField(max_length=250)),
                ('info', models.TextField(verbose_name='Additional Info')),
                ('inactive', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Designation')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Division')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
